CREATE DATABASE jdbc_ex;

CREATE USER 'scoula'@'%' IDENTIFIED BY '1234';

GRANT ALL PRIVILEGES ON jdbc_ex.* TO 'scoula'@'%';

FLUSH PRIVILEGES;

use jdbc_ex;

CREATE TABLE USERS
(
    ID       VARCHAR(12) NOT NULL PRIMARY KEY,
    PASSWORD VARCHAR(12) NOT NULL,
    NAME     VARCHAR(30) NOT NULL,
    ROLE     VARCHAR(6)  NOT NULL
);
INSERT INTO USERS(ID, PASSWORD, NAME, ROLE)
VALUES ('guest', 'guest123', '방문자', 'USER');
INSERT INTO USERS(ID, PASSWORD, NAME, ROLE)
VALUES ('admin', 'admin123', '관리자', 'ADMIN');
INSERT INTO USERS(ID, PASSWORD, NAME, ROLE)
VALUES ('member', 'member123', '일반회원', 'USER');

SELECT * FROM USERS;

CREATE TABLE ORDERS
(
    NO     INT AUTO_INCREMENT PRIMARY KEY,
    USERID VARCHAR(12) NOT NULL,
    TOTAL  INT         NOT NULL,
    FOREIGN KEY (USERID)
    REFERENCES USERS(ID)
);

INSERT INTO ORDERS VALUES (NULL, 'guest', 10000);
INSERT INTO ORDERS VALUES (NULL, 'admin', 20000);
INSERT INTO ORDERS VALUES (NULL, 'member', 30000);

SELECT * FROM ORDERS;

SELECT U.ID, U.NAME, O.NO, O.TOTAL
FROM USERS U
INNER JOIN ORDERS O
ON U.ID = O.USERID;